DataDog/autoscaler

cluster-autoscaler/cloudprovider/aws/auto_scaling.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x176d90f]
goroutine 149 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.autoScalingWrapper.populateLaunchConfigurationInstanceTypeCache(0x36e7fa0, 0xc00067e0c0, 0x0, 0xc00251fef0, 0xc02d670000, 0x3ee, 0x400, 0x0, 0x0)
/go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/auto_scaling.go:54 +0x18f
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*asgCache).regenerate(0xc000712480, 0x0, 0x0)
/go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:369 +0x2f4
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).forceRefresh(0xc002018dc0, 0xc002018dc0, 0x0) …
```
=> cluster-autoscaler/cache: ignore potential nil pointers

cluster-autoscaler/core/filter_out_schedulable.go
A pod might not specify resources `Requests` or `Limits`; in which
case those apiv1.ResourceList maps are uninitialised.
We should ensure both those `ResourceRequirements` fields are
initialised before appending our "storageClass/local-data" resource.
Else, we crash with a 
```
panic: assignment to entry in nil map
```
=> Support Pods without explicit resources requests or limits

cluster-autoscaler/FAQ.md, cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Cherry picked changes (from upstream/master) required to:
* Retrieve secrets from the cloud config file instead of env vars
* Be gentle on Azure Scale Set API endpoints. At least, don't trigger rate limits immediately.
* Actually scale up and down tagged scale sets (autodiscovery was broken)
Those commits are exclusively targeting `cloudprovider/azure` (save for a FAQ.md change): they shouldn't affect CA running on other cloud providers:
```
$ git diff --stat datadog/datadog-master..
cluster-autoscaler/FAQ.md                                           |   2 +-
cluster-autoscaler/cloudprovider/azure/README.md                    |   5 ++++-
cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go          |  41 +++++++++++++++++++++++++++++++++++++---- …
```
=> Azure support

cluster-autoscaler/cloudprovider/aws/aws_manager.go
AWS API `DescribeInstanceTypes` API (as used by the autoscaler) returns
memory capacities as proper BinarySI values. This replaced chunk seemed
to try to convert megabytes to mebibytes (guessed from the classic 1.049
factor). For larger instance types this amount to a significant
unclaimable memory (eg. i3.8xlarge has 244GiB but with the replaced
chunk, the autoscaler only saw 232GiB).
=> Fix AWS memory capacity estimations

cluster-autoscaler/core/utils/get_full_nodeinfo.go, cluster-autoscaler/processors/nodeinfos/template_only_node_info_processor.go
Caches locks from concurrent refreshes causes significant slowdowns in
utils.GetNodeInfoFromTemplate(), as called by the nodeInfos processor
(or previously, by GetNodeInfosForGroups()). Just caching the nodeInfos
isn't enough: a single invalidated/expired cache entry causing a single
MIG refresh is enough for the processor to be locked for 30s to 6m+ at
every RunOnce loop, slowing down main loop by ~250% on large clusters.
This only affects GCP cloud-provider (having coarse grained caches,
invalidated from multiple concurrent goroutines, and a slow API).
Keeping the local nodeInfos cache up-to-date async in background allows
instant processing while at the same time permit more frequent refreshes
(useful to pick labels changes in ASG/MIGs early).
That's hardly upstreamable (nodeinfo …
=> local only: gcp perf improvement on large MIG count

cluster-autoscaler/main.go, cluster-autoscaler/processors/datadog/pods/filter_out_schedulable.go, cluster-autoscaler/processors/datadog/pods/filter_out_schedulable_test.go
This is an unmodified (except for package name) copy of the `core/filter_out_schedulable*` as of current `datadog-master-3.0` branch's HEAD.
Goal is to miminize upstream code changes in this fork: this supersedes e9a967ab8f23cd5bf94d7889c1b495bad483c660 and 721728ce40daa95838521991c35d675e1e810310 patches which we'll drop soon.
Those files (the pod list processor) embed our most non-upstreamable code changes (support for local volumes and old cluster without TBE).
This also gives a foothold for some local-only improvements, without touching upstream code; plans includes:
* Runaway upscale prevention
* Schedulable metrics (pending pods pressure, long pending pods)
* Pods labels selectors (for dedicated autoscaler instances)
* Possibly: un-priorise pods from cronjobs
Not cleaning-up or …
=> clarify datadog's own podlistprocessor

cluster-autoscaler/processors/datadog/pods/filter_long_pending.go, cluster-autoscaler/processors/datadog/pods/filter_long_pending_test.go, cluster-autoscaler/processors/datadog/pods/filter_schedulable.go, cluster-autoscaler/processors/datadog/pods/processor.go, cluster-autoscaler/processors/datadog/pods/utils.go, cluster-autoscaler/processors/datadog/pods/utils_test.go
Goals of that PodListProcessor are twofold:
* Lower presure on runonce loops by evaluating long pending pods less frequently
* More importantly: free autoscaler cycles to recover from scaledown cooldown, so nodes created for pods causing infinite upscales get gc'ed rather than filling a cluster (and those pods are slowed down)
The delay penalty could be made progressive (eg. 2m then 5m then 10m etc), but for now a static value makes evaluating benefits and impacts easier.
Metrics to come in follow-up PR.
=> [local only] Long pending pods filter

cluster-autoscaler/main.go, cluster-autoscaler/processors/datadog/pods/filter_long_pending.go, cluster-autoscaler/processors/datadog/pods/filter_long_pending_test.go, cluster-autoscaler/processors/datadog/pods/filter_schedulable.go, cluster-autoscaler/processors/datadog/pods/filter_schedulable_test.go, cluster-autoscaler/processors/datadog/pods/processor.go, cluster-autoscaler/processors/datadog/pods/processor_test.go, cluster-autoscaler/processors/datadog/pods/transform_local_data.go, cluster-autoscaler/processors/datadog/pods/transform_local_data_test.go, cluster-autoscaler/processors/datadog/pods/utils.go, cluster-autoscaler/processors/datadog/pods/utils_test.go
This is only moving existing code around (not functional changes)
in order to introduce a processor frontend (processor.go) that allows
chaining filters and transformations.
While at it, bring unit tests for our local changes.
New functionalities in follow-up PRs.
=> [local only] Introduce a PodListProcessor frontend

cluster-autoscaler/processors/datadog/pods/filter_schedulable.go
Taint based eviction default tolerationSeconds is 300s; let's configure
something closer to that.
=> [local only] Set dead node detection deadline to TBE default

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/utils/scheduler/scheduler.go
Both upscale's `getUpcomingNodeInfos` and the binpacking estimator now uses
the same shared `DeepCopyTemplateNode` function and inherits its naming
pattern, which is great and fixes a long standing bug.
Due to that, `getUpcomingNodeInfos` will enrich the cluster snapshots with
generated nodeinfos and nodes having predictable names (using the nodegroup's
template name, and an incremental ordinal starting at 0) for upcoming nodes.
Later, when it looks for fitting nodes for unschedulable pods (when upcoming
nodes don't satisfy those (FitsAnyNodeMatching failing due to nodes capacity,
or pods antiaffinity, ...), the binpacking estimator will also build virtual
nodes and place them in a snapshot fork to evaluate scheduler predicates.
Those temporary virtual nodes are built using the same …
=> Fix templated nodeinfo names collisions in BinpackingNodeEstimator

cluster-autoscaler/processors/datadog/common/common.go, cluster-autoscaler/processors/datadog/common/common_test.go, cluster-autoscaler/processors/datadog/pods/transform_local_data_test.go
This is meant to isolate, contain and wrap access to our custom
resource (storageclass/local-data) and label (/local-storage)
in a single place, separated in our processors/datadog/ namespace.
Avoid spreading local names and constraints over all the code base.
=> [local] Define Datadog custom variables and accessors

cluster-autoscaler/processors/datadog/pods/transform_local_data.go, cluster-autoscaler/processors/datadog/pods/transform_local_data_test.go
Keep everything scoped to our own/local PodList and NodeInfos Processors.
This replace a previous patch that was setting this in the core
autoscaler lister registry, which was a correct place, but very
intrusive for a local-only change (for instance, that previous
version impacted most upstream unit tests).
=> [local] Instanciate pvc lister in our podListProcessor

cluster-autoscaler/processors/nodeinfos/template_only_node_info_processor.go
This relies on the local-data:true label to inject the local-data
Datadog custom resources on virtual nodes built for NodeInfo templates.
Replaces a previous patch that was setting this from each cloud
provider (on `TemplateNodeInfo()` calls), using allow lists of
instances types with local storage.
=> [local] Scope nodes custom resource injection to our nodeinfos processor

cluster-autoscaler/processors/datadog/pods/filter_schedulable.go, cluster-autoscaler/processors/datadog/pods/processor.go, cluster-autoscaler/processors/datadog/pods/transform_nodes_local_data.go, cluster-autoscaler/processors/datadog/pods/transform_nodes_local_data_test.go
This is meant to replace a patch that was setting new nodes as NotReady
until their lvp pod was there, with something bound to and contained in
our podsListProcessor, not touching autoscaler core or cloudproviders at
all anymore. Decision is entirely based of the local-data:true label: no
guessing or per cloud provider instances types allowlists needed anymore.
Instead of setting them NotReady, the new nodes that just joined are now
considered as schedulable for pods requesting local-data once they are
ready, which naturaly prevents spurious re-upscales.
For now the change is restricted to new local-data nodes that just became
ready for less than 5mn, as we're assessing wider impact.
The downside is we need to modify the clusterSnapshot content before
filterOutSchedulable runs scheduler …
=> [local] Set local-data custom resource on fresh nodes

cluster-autoscaler/processors/datadog/nodeinfosprovider/template_only_node_info_provider.go, cluster-autoscaler/processors/datadog/nodeinfosprovider/template_only_node_info_provider_test.go
[Recent upstream changes](https://github.com/kubernetes/autoscaler/commit/8f11490c0c85fcab493af2538b4f51b0c6c72489)
dropped the pre-stable nodes labels (eg. `failure-domain.beta.kubernetes.io/zone`) injection
from cloud providers. Instead, cloud providers are now configured to only
set stable labels (eg. `topology.kubernetes.io/zone`), while `GetNodeInfoFromTemplate`
would mirror (backfill) those stable labels to their pre-stable counterpart
in the generated nodeInfos the autoscaler will use for scheduler evaluations.
This fork doesn't use `GetNodeInfoFromTemplate` at all; before it can be
rebased again, we have to replicate upstream changes in its own nodeinfo
processor to restore pre-stable labels (that might be used by pod's
nodeselectors, affinities, or spread constraints).
=> [local] backfill pre-stable node labels

cluster-autoscaler/main.go, cluster-autoscaler/processors/datadog/nodeinfosprovider/template_only_node_info_provider.go, cluster-autoscaler/processors/datadog/nodeinfosprovider/template_only_node_info_provider_test.go
No functional changes: this only makes TemplateOnlyNodeInfoProvider conformant to the new TemplateNodeInfoProvider interface. This allows for a cleaner integration with the core autoscaler.
Also: SanitizeTemplateNode and SanitizeNodeInfo are now exported (from core/utils) function, no need to keep a local copy anymore.
nb: the patch that hooked the previous implementation to core+processor is already dropped (to keep a clean history and not having to cope with that obsolete and intrusive patch during future rebases to upstream/master).
=> [local] Adopt new TemplateOnlyNodeInfoProvider interface

cluster-autoscaler/processors/datadog/pods/filter_schedulable.go, cluster-autoscaler/processors/datadog/pods/filter_schedulable_test.go, cluster-autoscaler/processors/datadog/pods/processor.go
Resync with upstream's `core/filter_out_schedulable.go` recent changes: no new local features, just changes to reduce drift. After this diff, and reflecting a change from upstream, having pending pods around won't block downscales.
That custom processor now only differs (from upstream filter_out_schedulable.go) on two ways:
* It avoid `NodeReady` nodes blocking upscales where taint based eviction isn't there (eg. older kubernetes versions)
* It accounts for filtered out long pending pods (which doesn't matter much now that pending pods don't inhibit downscales, so this chunk might go away on future revisions)
Here's what remains different (`diff -u  core/filter_out_schedulable.go ./processors/datadog/pods/filter_schedulable.go`): …
=> [local] resync schedulable filters with upstream

cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go
/!\ This is an unfortunately unavoidable change to vendor/, not meant to stay indefinitely.
Implementation tries to be non intrusive and to avoids refactoring and ease future rebases; that change should be removed when the cluster-autoscaler don't need to support Kubernetes clusters < k8s v1.24 anymore.
The spreadtopology constraints' skew accounting changed slightly, which can lead cluster-autoscaler (>= 1.24) to leave pending pods on k8s clusters < 1.24:
When evaluating nodes options for a pending pod having topology spread constraints, Kubernetes used (and continues) to inventory all the possible topology domains (eg. zones us-east-1a, us-east-1b, etc which it will try to use in a balanced way, with respect to the configured skew) by listing nodes running pods matching the provided …
=> [local] Backward compatible spread topology - hack

cluster-autoscaler/processors/datadog/common/common.go, cluster-autoscaler/processors/datadog/common/common_test.go, cluster-autoscaler/processors/datadog/pods/transform_local_data.go, cluster-autoscaler/processors/datadog/pods/transform_local_data_test.go
In order to support more fine grained local storage, we are currently investigating different solutions like [topolvm](https://github.com/topolvm/topolvm) or [openebs](https://github.com/openebs/openebs).
One of the most important requirement is that the new solution should also support autoscaling. So, this is the first draft to implement a pretty straight forward way to tell the autoscaler all the information it needs to figure out which node group can support what storage requirements.
=> First draft to support lvm storage (topolvm)

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
Upstream PR: https://github.com/kubernetes/autoscaler/pull/5247
=> Cherry-pick: add extended resource support in GCE

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/enhancements/xxxx-update-mode-trigger/README.md, vertical-pod-autoscaler/examples/hamster-workload.yaml, vertical-pod-autoscaler/hack/generate-crd-yaml.sh, vertical-pod-autoscaler/pkg/admission-controller/README.md, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/admission-controller/resource/deployment/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/deployment/handller_test.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/update_trigger.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/update_trigger_test.go, vertical-pod-autoscaler/pkg/admission-controller/resource/statefulset/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/admission-controller/resource/workloads/utils.go, vertical-pod-autoscaler/pkg/admission-controller/resource/workloads/utils_test.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/utils/annotations/vpa_trigger.go, vertical-pod-autoscaler/pkg/utils/annotations/vpa_trigger_test.go, vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go
vertical-pod-autoscaler
/kind feature
/kind api-change
Setting the `vpaTrigger:true` annotation will trigger a recommendation
on a pod, deployment or statefulset.
See vertical-pod-autoscaler/enhancements/xxxx-update-mode-trigger/README.md
=> vpa/admission-controller: add UpdateMode 'Trigger'

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go
There's a small window between the time the ASG list is refreshed (happens every 1mn), and the time expired or new instance-types cache entries are fetched again from ASG's LaunchConfigurations or LaunchTemplates.
An ASG's LC might have been replaced during that window; in which case attempts to refresh that ASG instance-type would use the stale LC name we got when we last ASGs list, possibly deleted since then.
DescribeLaunchConfigurations would not err if some of the provided LaunchConfigurationNames are missing from the result set. Which is fine as we can cache what we could retrieve, and try again/converge the missing entries once we retry with a refreshed ASG list (at most 1mn in the future), avoiding collecting everything again (expansive API calls).
The issue is …
=> [local] AWS: don't cache empty instance-types

cluster-autoscaler/main.go, cluster-autoscaler/processors/datadog/pods/processor.go
Adds the `CurrentlyDrainedNodesPodListProcessor` into the list of filters supported by the Datadog pods processor. This was introduced upstream in https://github.com/kubernetes/autoscaler/pull/5354/files and should add a small optimization for pods considered unschedulable.
Also fixes an indentation issue from running `./hack/update_gofmt.sh`
=> [local] Add currently draining pod filter into Datadog podlistprocessor

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/examples/hamster-external-metrics.yaml, vertical-pod-autoscaler/pkg/recommender-external/Dockerfile, vertical-pod-autoscaler/pkg/recommender-external/input/annotations.go, vertical-pod-autoscaler/pkg/recommender-external/input/annotations_test.go, vertical-pod-autoscaler/pkg/recommender-external/input/metrics/annotations_test.go, vertical-pod-autoscaler/pkg/recommender-external/input/metrics/external_metrics_client.go, vertical-pod-autoscaler/pkg/recommender-external/input/metrics/external_metrics_client_test.go, vertical-pod-autoscaler/pkg/recommender-external/input/metrics/external_metrics_client_test_util.go, vertical-pod-autoscaler/pkg/recommender-external/input/recommendations_feeder.go, vertical-pod-autoscaler/pkg/recommender-external/input/recommendations_feeder_test.go, vertical-pod-autoscaler/pkg/recommender-external/logic/recommender.go, vertical-pod-autoscaler/pkg/recommender-external/routines/recommender.go, vertical-pod-autoscaler/pkg/recommender-external/routines/vpa.go, vertical-pod-autoscaler/pkg/recommender/model/vpa.go, vertical-pod-autoscaler/vendor/k8s.io/metrics/pkg/client/external_metrics/fake/fake_client.go, vertical-pod-autoscaler/vendor/modules.txt
An example has been added to `vertical-pod-autoscaler/examples/hamster-external-metrics.yaml` This is a minimal version that reads external metrics every minutes and applies them as recommendations.
Proof that it works:
```
$ k get datadogmetrics,vpa
NAME                                         ACTIVE   VALID   VALUE        REFERENCES                     UPDATE TIME
datadogmetric.datadoghq.com/hamster-cpu      True     True    504.120848   hpa:default/hpa-fake-hamster   2m37s
datadogmetric.datadoghq.com/hamster-memory   True     True    12401664     hpa:default/hpa-fake-hamster   2m37s
NAME                                                   MODE       CPU    MEM    PROVIDED   AGE
verticalpodautoscaler.autoscaling.k8s.io/hamster-vpa   Recreate   580m   50Mi   True       9d
```
``` …
```
=> recommender-external: start reading external metrics

vertical-pod-autoscaler/pkg/admission-controller/resource/workloads/utils.go
Fix a panic when the pod spec has no annotation
=> vpa-admisssion-controller: don't panic on pod without any annotations

cluster-autoscaler/cloudprovider/aws/aws_manager.go
[Cherry-pick of upstream's [#5550](https://github.com/kubernetes/autoscaler/pull/5550)]
In order to support optional InstanceRequirements (attribute-based instance type selection) specifications for ASGs using LaunchTemplates (and not directly specifying those InstanceRequirements inline within the ASG), the cluster-autoscaler's AWS cloud provider was recently improved to look for possible requirements by retrieving LaunchTemplates and their versions, when it builds NodeInfos templates.
With LaunchTemplates, the new NodeInfos generation code flows like so:
```
GetNodeInfoFromTemplate()
TemplateNodeInfo()
buildNodeFromTemplate()
updateCapacityWithRequirementsOverrides()
getInstanceRequirementsFromMixedInstancesPolicy()
// when ASG doesn't specify an instanceRequirementsOverrides inline,
// …
```
=> AWS: only look for InstanceRequirements when needed

vertical-pod-autoscaler/pkg/recommender-external/main.go
This register missing metrics to the vpa-recommender-external
=> [local] vpa-recommender-external: register missing metrics

vertical-pod-autoscaler/pkg/recommender-external/main.go, vertical-pod-autoscaler/pkg/recommender-external/routines/recommender.go, vertical-pod-autoscaler/pkg/recommender-external/routines/recommender_test.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client_test_util.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/routines/cpu_integer_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/recommender/routines/resource_ratio_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/resource_ratio_post_processor_test.go
This is a local patch that match upstream PR:
https://github.com/kubernetes/autoscaler/pull/5679
There is a bit of conflict resolution and adaptation done in the external-metrics recommender since some constructor functions have been deprecated/removed.
=> [local] resource ratio post processor on top of vpa 0.13.0

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Fixes an issue where the autoscaler would sometimes scale down in-use azure nodes. This was occurring during large scale ups, where Azure was reporting networking provisioning failures.  
```json
{
"code": "ProvisioningState/failed/NetworkingInternalOperationError",
"level": "Error",
"displayStatus": "Provisioning failed",
"message": "An unexpected error occured while processing the network profile of the VM. Please retry later.",
"time": "2023-05-09T21:02:25.8112918Z"
},
{
"code": "PowerState/running",
"level": "Info",
"displayStatus": "VM running"
}
```
This PR adds support to check the power state if a failed provisioning is reported.  If the VM is running, the instance is reported as running and no OutOfResource error is set. If the VM does not report a power status or has a stopping …
=> Check PowerState on provisioning failures

vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_datadog_client.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
At some point the code is indexing the metrics by timestamp. The problem is that CPU and MEM queries are made in sequence and on big clusters the reply is ~250Mo and takes time to be captured for each query... to point where we have no intersection between the CPU and MEM time window in the response.
For the moment (and this is another problem) the recommender fails if CPU or MEM is missing. I will fix this later. With this PR I just want to make a small step to ensure that we have point for both CPU and MEM at a given common point in time. In a next PR I will refactor the code to handle every resource independently one from the other (user can request reco only for one resource).
This should solve the problem we are having now on `psyduck`. Potentially we will have to reset all …
=> [recommender] ensure that CPU and Mem are fetch on the same time window

vertical-pod-autoscaler/FAQ.md, vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/safety_margin_modifier_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/safety_margin_modifier_post_processor_test.go
vertical-pod-autoscaler
/kind feature
By default, the VPA recommender adds a safety margin of 15% to its CPU and Memory recommendation which can be adjusted by passing the `recommendation-margin-fraction` flag to the invocation command. However,
this parameter is unique and applies to all VPAs under the recommender. Some application would benefit from a different safety margin. Moreover, one may want to pass the recommendation through a custom function
(e.g.: affine, log).
When enabled, this post-processor reads the `vpa-post-processor.kubernetes.io/{containerName}_safetyMarginModifier` annotation of VPA objects and apply the given custom safety marging modifier post processor
Available functions:
Name | Parameters | Formula | Description
|-|-|-|-|
| Linear | [slope] | slope \* …
=> Safety Margin Modifier Post Processor 

vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/resource_ratio_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/resource_ratio_post_processor_test.go
Change the api for the ratio post-processor:
`{"cpu":{"resource":"memory","ratio":15000000}}`
if the ratio is not specified, the one in the podTemplate is used:
`{"cpu":{"resource":"memory"}}`
=> [local] new syntax to define ratio inside the annotation

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go, vertical-pod-autoscaler/pkg/utils/test/test_recommendation.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go
prevent admission to inject corrupted VPA object that would contain a recommendation for a resource that has an empty key like here:
```
recommendation:
containerRecommendations:
- containerName: event-context-publisher
lowerBound:
"": "0"
cpu: "1"
target:
"": "0"
cpu: "1"
uncappedTarget:
cpu: "1"
upperBound:
"": "0"
cpu: "1"
```
=> protect admission against empty keys

vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/pkg/utils/vpa/allowed_resource_filter.go, vertical-pod-autoscaler/pkg/utils/vpa/allowed_resource_filter_test.go, vertical-pod-autoscaler/pkg/utils/vpa/recommendation_processor.go
Adds a new recommendation post-processor that restricts which recommended resources can actually be applied to a pod. This is useful for preventing new/experimental recommendations from immediately being applied, as well as preventing intermediate values without a backing extended resource from being applied.
It's implemented as a RecommendationProcessor; I'm using the existing (but previously unused) SequentialProcessor to hook in the Capping processor (which was previously the only RecommendationProcessor used) and this new AllowedResourceFilter.
It's gated by a command line option `--allowed-resources` in both the updater and admission controller. By default, this should be no change from the current behavior where only cpu/memory are applied.
=> [vertical-pod-autoscaler] Add AllowedResourceFilter to restrict which recommendations can be applied

vertical-pod-autoscaler/pkg/utils/vpa/allowed_resource_filter.go, vertical-pod-autoscaler/pkg/utils/vpa/allowed_resource_filter_test.go
Fixes an issue where a nil recommendation would attempt to be iterated over. This takes similar logic from the capping processor.
=> Bugfix: Check recommendation is non-nil before iterating

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates_test.go
Extended resources must be qualified by domain (e.g. example.com/dongle). The special '/' must be properly escaped the patch to be properly applied.
This was previously causing errors like:
```
'Internal error occurred: add operation does not apply: doc is missing path: "/spec/containers/0/resources/requests/kubernetes.io/network-bandwidth": missing value'
```
Needing to escape the strings is documented [here](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/)
=> Use IETF-6901 encoding for resource patches

vertical-pod-autoscaler/pkg/utils/vpa/allowed_resource_filter.go
Fixes an issue introduced in https://github.com/DataDog/autoscaler/pull/105; I originally added an additional nil check for the `resourcePolicy` field from the VPA, based on the similar checks in the capping processor.  However, this resulted in a case where the filtering processor would have a recommendation set but no policy, and exit without removing the fields that needed to be filtered.
This removes that erroneous check.
=> [bugfix] Remove erroneous policy check

.github/workflows/ci.yaml, cluster-autoscaler/main.go
That branch (and really, cluster-autoscaler-1.28.x) won't pass CI
anymore as its `GO111MODULE=auto` will break with golang >= 1.21,
yet the CI specified `'>=1.20.0'`, so it broke when a newer version
of `actions/setup-go` was provided.
Also fix a gofmt issue on that breaks on newer versions.
=> Fix CI for master-1.12 branch

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Fixes an issue where deletion tracking would sometimes lose track of an instance that had already had a deletion submitted, which would lead to too many scale downs. The general flow that would cause this is:
* Deletion requested for a VM, which sets the state as InstanceDeleting and decrements size
- The API call is slow and does not immediately transition the instance to actually deleting
* A rebuild of the instance cache occurs, which sets the instance state to its 'real' value (e.g. Running)
* Deletion is requested again; size is decremented _again_ and state is set as InstanceDeleting again
- This repeats until the API calls actually go through
This would cause issues if multiple deletes were triggered and then upscale was triggered while the current size was vastly out of sync with …
=> Track previous deletions when cache is refreshed

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Adds an option `AZURE_VMSS_CACHE_FORCE_REFRESH` to force the refresh of the VMSS cache (not VMSS VMs cache per scale set) before an upscale is triggered. This ensures that the size that will be considered during the upscale is up to date, and minimizes the potential for skew in accounting by relying on `scaleSet.curSize`.
This also adds a check and some more logging on the upscale path to ensure that an 'upscale' to a size that's lower than the current size is never attempted, as this would always delete random instances.
=> Force refresh before IncreaseSize

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Cherry-picks the following changes:
* https://github.com/kubernetes/autoscaler/pull/7065/commits/9ed9b461377b41bf70c0460addc89084810bd418
* https://github.com/kubernetes/autoscaler/pull/7087/commits/939123cb6960f1a87d216481f439a6f1aff6b5b4
The former is by the same author and is a precursor for 7087; it makes the cherry-pick cleaner (only one small conflict in the unit tests for static_autoscaler_test vs several in the main body of static_autoscaler.
This should resolve an issue where the CA stops upscaling for the whole cluster when a single VMSS is stuck in a failed state.
=> cherry-pick 7065, 7087 into datadog-master-13.0 (handle failed nodegroups better)

cluster-autoscaler/main.go
Adds a call to WaitForCacheSync after the sharedInformerFactory has been started; This will help remediate against cases where the API server is (partially) unavailable and prevent empty, unsynced cache data from being served to consumers.
=> [local] Wait for initial cache to sync before starting autoscaling
